apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: briy8w0hx-java-quarkus
  janus-idp.io/tekton: briy8w0hx-java-quarkus
  backstage.io/kubernetes-id: briy8w0hx-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: briy8w0hx-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
